### PR TITLE
Serve the home directory

### PR DESCRIPTION
**Pull request by johannesjasper**
I used your image to serve multiple directories (each with an index.html).
These changes allow serving the content of the root directory in a browser.

### CODE REVIEW

**Comment by tobilg** [comment]
HI @johannesjasper and thanks for the PR. As far as I can see, you don't require `serveIndex` which probably would yield in an error...

Also, I would really like to be able to enable this functionality via environment variable, because there are use cases where I don't want to enable directory browsin

**Comment by johannesjasper** [comment]
Hey @tobilg , thanks for the feedback. You're right of course, I completely forgot the `require`.
I also added a switch to disable the feature, please have a look at that.
Cheers

**Review by tobilg — CHANGES_REQUESTED** [review]
Hi! Thanks again for the changes! I'd really want to see the if-statement logic to be reversed, sorry, I should have been clearer before:

E.g. `if (process.env.SERVE_DIRECTORY_INDEX && process.env.SERVE_DIRECTORY_INDEX.toLowerCase() === 'true')`.

Also, it would be nice to add a remark in the README about the `SERVE_DIRECTORY_INDEX` env variable. Thanks!

**Comment by johannesjasper** [comment]
stale

**Pull request closed without merging**
